# FROM golang:1.20-alpine
FROM golang:1.25-alpine

WORKDIR /go/src/app



RUN apk update && \
    apk upgrade && \
    apk add --no-cache git jq

# dev ---> RUN go install github.com/air-verse/air@latest

COPY . .
RUN go get gorm.io/datatypes

RUN go mod tidy
RUN go mod download

# dev---> CMD ["air"]
CMD ["go", "run", "main.go"]